import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <nav className="navigate">
              <button>
            <Link href="/"> Home </Link>
            </button>
            <button>
            <Link href="/start"> Start </Link>
            </button>
            </nav>
        {children}
        </body>
        <footer className="footer">
        <ul class="contact-us">
            <div class="contact-icons-container">
                <li class="contact-icons"><a href=""><img src="app/SVG/Icons/telephone.svg" alt=""></img></a></li>
                <li class="contact-icons"><a href=""><img src="app/SVG/Icons/facebook.svg" alt=""></img></a></li>
                <li class="contact-icons"><a href="https://www.linkedin.com/feed/"><img src="app/SVG/Icons/instagram.svg" alt=""></img></a></li>
            </div>
        </ul>
   
  </footer>
    </html>
  );
}
